# Generated by Django 5.2.1 on 2025-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('author_title', models.CharField(blank=True, max_length=256, null=True)),
                ('date_published', models.CharField(blank=True, max_length=64, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.TextField()),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('image_credit', models.CharField(blank=True, max_length=256, null=True)),
                ('categories', models.CharField(blank=True, max_length=512, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=32, null=True)),
                ('scrape_timestamp', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
