# Generated by Django 5.2.1 on 2025-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rewritten_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
