# Generated by Django 5.2.1 on 2025-06-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_rewritten_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='structured_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
