services:
  # A Django web service
  - type: web
    name: travelpoints
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn travelpoints.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: travelpoints.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: travelpoints-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: travelpoints-db
    databaseName: travelpoints
    user: travelpoints
    plan: free 